error: [2020-03-19 12:41:28] CastError: Cast to string failed for value "Promise {,  {,    filename: 'welcome.jpg',,    mimetype: 'image/jpeg',,    encoding: '7bit',,    createReadStream: [Function: createReadStream],  },}" at path "imageFileName",    at new CastError (D:\Projects\task\node_modules\mongoose\lib\error\cast.js:39:11),    at SchemaString.cast (D:\Projects\task\node_modules\mongoose\lib\schema\string.js:606:11),    at SchemaString.SchemaType.applySetters (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1010:12),    at SchemaString.SchemaType._castForQuery (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1424:15),    at SchemaString.castForQuery (D:\Projects\task\node_modules\mongoose\lib\schema\string.js:668:15),    at SchemaString.SchemaType.castForQueryWrapper (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1393:15),    at castUpdateVal (D:\Projects\task\node_modules\mongoose\lib\helpers\query\castUpdate.js:515:19),    at walkUpdatePath (D:\Projects\task\node_modules\mongoose\lib\helpers\query\castUpdate.js:342:22),    at castUpdate (D:\Projects\task\node_modules\mongoose\lib\helpers\query\castUpdate.js:99:18),    at model.Query._castUpdate (D:\Projects\task\node_modules\mongoose\lib\query.js:4482:10),    at castDoc (D:\Projects\task\node_modules\mongoose\lib\query.js:4510:18),    at model.Query._updateThunk (D:\Projects\task\node_modules\mongoose\lib\query.js:3709:20),    at model.Query.<anonymous> (D:\Projects\task\node_modules\mongoose\lib\query.js:3804:23),    at model.Query._wrappedThunk [as _updateOne] (D:\Projects\task\node_modules\mongoose\lib\helpers\query\wrapThunk.js:16:8),    at D:\Projects\task\node_modules\kareem\index.js:369:33,    at processTicksAndRejections (internal/process/task_queues.js:75:11)
error: [2020-03-19 12:45:56] CastError: Cast to string failed for value "Promise {,  {,    filename: 'welcome.jpg',,    mimetype: 'image/jpeg',,    encoding: '7bit',,    createReadStream: [Function: createReadStream],  },}" at path "imageFileName",    at new CastError (D:\Projects\task\node_modules\mongoose\lib\error\cast.js:39:11),    at SchemaString.cast (D:\Projects\task\node_modules\mongoose\lib\schema\string.js:606:11),    at SchemaString.SchemaType.applySetters (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1010:12),    at SchemaString.SchemaType._castForQuery (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1424:15),    at SchemaString.castForQuery (D:\Projects\task\node_modules\mongoose\lib\schema\string.js:668:15),    at SchemaString.SchemaType.castForQueryWrapper (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1393:15),    at castUpdateVal (D:\Projects\task\node_modules\mongoose\lib\helpers\query\castUpdate.js:515:19),    at walkUpdatePath (D:\Projects\task\node_modules\mongoose\lib\helpers\query\castUpdate.js:342:22),    at castUpdate (D:\Projects\task\node_modules\mongoose\lib\helpers\query\castUpdate.js:99:18),    at model.Query._castUpdate (D:\Projects\task\node_modules\mongoose\lib\query.js:4482:10),    at castDoc (D:\Projects\task\node_modules\mongoose\lib\query.js:4510:18),    at model.Query._updateThunk (D:\Projects\task\node_modules\mongoose\lib\query.js:3709:20),    at model.Query.<anonymous> (D:\Projects\task\node_modules\mongoose\lib\query.js:3804:23),    at model.Query._wrappedThunk [as _updateOne] (D:\Projects\task\node_modules\mongoose\lib\helpers\query\wrapThunk.js:16:8),    at D:\Projects\task\node_modules\kareem\index.js:369:33,    at processTicksAndRejections (internal/process/task_queues.js:75:11)
error: [2020-03-19 12:46:00] CastError: Cast to string failed for value "Promise {,  {,    filename: 'welcome.jpg',,    mimetype: 'image/jpeg',,    encoding: '7bit',,    createReadStream: [Function: createReadStream],  },}" at path "imageFileName",    at new CastError (D:\Projects\task\node_modules\mongoose\lib\error\cast.js:39:11),    at SchemaString.cast (D:\Projects\task\node_modules\mongoose\lib\schema\string.js:606:11),    at SchemaString.SchemaType.applySetters (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1010:12),    at SchemaString.SchemaType._castForQuery (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1424:15),    at SchemaString.castForQuery (D:\Projects\task\node_modules\mongoose\lib\schema\string.js:668:15),    at SchemaString.SchemaType.castForQueryWrapper (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1393:15),    at castUpdateVal (D:\Projects\task\node_modules\mongoose\lib\helpers\query\castUpdate.js:515:19),    at walkUpdatePath (D:\Projects\task\node_modules\mongoose\lib\helpers\query\castUpdate.js:342:22),    at castUpdate (D:\Projects\task\node_modules\mongoose\lib\helpers\query\castUpdate.js:99:18),    at model.Query._castUpdate (D:\Projects\task\node_modules\mongoose\lib\query.js:4482:10),    at castDoc (D:\Projects\task\node_modules\mongoose\lib\query.js:4510:18),    at model.Query._updateThunk (D:\Projects\task\node_modules\mongoose\lib\query.js:3709:20),    at model.Query.<anonymous> (D:\Projects\task\node_modules\mongoose\lib\query.js:3804:23),    at model.Query._wrappedThunk [as _updateOne] (D:\Projects\task\node_modules\mongoose\lib\helpers\query\wrapThunk.js:16:8),    at D:\Projects\task\node_modules\kareem\index.js:369:33,    at processTicksAndRejections (internal/process/task_queues.js:75:11)
error: [2020-03-19 12:46:57] CastError: Cast to string failed for value "Promise {,  {,    filename: 'welcome.jpg',,    mimetype: 'image/jpeg',,    encoding: '7bit',,    createReadStream: [Function: createReadStream],  },}" at path "imageFileName",    at new CastError (D:\Projects\task\node_modules\mongoose\lib\error\cast.js:39:11),    at SchemaString.cast (D:\Projects\task\node_modules\mongoose\lib\schema\string.js:606:11),    at SchemaString.SchemaType.applySetters (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1010:12),    at SchemaString.SchemaType._castForQuery (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1424:15),    at SchemaString.castForQuery (D:\Projects\task\node_modules\mongoose\lib\schema\string.js:668:15),    at SchemaString.SchemaType.castForQueryWrapper (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1393:15),    at castUpdateVal (D:\Projects\task\node_modules\mongoose\lib\helpers\query\castUpdate.js:515:19),    at walkUpdatePath (D:\Projects\task\node_modules\mongoose\lib\helpers\query\castUpdate.js:342:22),    at castUpdate (D:\Projects\task\node_modules\mongoose\lib\helpers\query\castUpdate.js:99:18),    at model.Query._castUpdate (D:\Projects\task\node_modules\mongoose\lib\query.js:4482:10),    at castDoc (D:\Projects\task\node_modules\mongoose\lib\query.js:4510:18),    at model.Query._updateThunk (D:\Projects\task\node_modules\mongoose\lib\query.js:3709:20),    at model.Query.<anonymous> (D:\Projects\task\node_modules\mongoose\lib\query.js:3804:23),    at model.Query._wrappedThunk [as _updateOne] (D:\Projects\task\node_modules\mongoose\lib\helpers\query\wrapThunk.js:16:8),    at D:\Projects\task\node_modules\kareem\index.js:369:33,    at processTicksAndRejections (internal/process/task_queues.js:75:11)
error: [2020-03-19 01:30:13] ValidationError: Post validation failed: imageFileName: Cast to String failed for value "Promise {,  'D:\\Projects\\task\\app/../staticFiles/images/0aa4a8e3-1578-49ff-8da6-6a48d0468718-nccvjom7pgi5jolixcza.jpg',}" at path "imageFileName",    at new ValidationError (D:\Projects\task\node_modules\mongoose\lib\error\validation.js:31:11),    at model.Document.invalidate (D:\Projects\task\node_modules\mongoose\lib\document.js:2552:32),    at model.$set (D:\Projects\task\node_modules\mongoose\lib\document.js:1233:12),    at model._handleIndex (D:\Projects\task\node_modules\mongoose\lib\document.js:971:14),    at model.$set (D:\Projects\task\node_modules\mongoose\lib\document.js:913:22),    at model.Document (D:\Projects\task\node_modules\mongoose\lib\document.js:135:12),    at model.Model (D:\Projects\task\node_modules\mongoose\lib\model.js:104:12),    at new model (D:\Projects\task\node_modules\mongoose\lib\model.js:4653:15),    at _callee3$ (D:\Projects\task\app/resolvers.js:63:27),    at tryCatch (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:45:40),    at Generator.invoke [as _invoke] (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:274:22),    at Generator.prototype.<computed> [as next] (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:97:21),    at asyncGeneratorStep (D:\Projects\task\app\resolvers.js:12:103),    at _next (D:\Projects\task\app\resolvers.js:14:194),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-19 01:30:29] GraphQLError: Variable "$image" of required type "Upload!" was not provided.,    at _loop (D:\Projects\task\node_modules\graphql\execution\values.js:92:17),    at coerceVariableValues (D:\Projects\task\node_modules\graphql\execution\values.js:119:16),    at getVariableValues (D:\Projects\task\node_modules\graphql\execution\values.js:48:19),    at buildExecutionContext (D:\Projects\task\node_modules\graphql\execution\execute.js:184:61),    at executeImpl (D:\Projects\task\node_modules\graphql\execution\execute.js:89:20),    at Object.execute (D:\Projects\task\node_modules\graphql\execution\execute.js:64:35),    at D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:481:30,    at Generator.next (<anonymous>),    at D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:8:71,    at new Promise (<anonymous>),    at __awaiter (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:4:12),    at execute (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:225:20),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:364:30),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-19 01:30:40] ValidationError: Post validation failed: imageFileName: Cast to String failed for value "Promise {,  'D:\\Projects\\task\\app/../staticFiles/images/1d31d6b9-3ca7-4381-a90d-508bc5784b09-nccvjom7pgi5jolixcza.jpg',}" at path "imageFileName",    at new ValidationError (D:\Projects\task\node_modules\mongoose\lib\error\validation.js:31:11),    at model.Document.invalidate (D:\Projects\task\node_modules\mongoose\lib\document.js:2552:32),    at model.$set (D:\Projects\task\node_modules\mongoose\lib\document.js:1233:12),    at model._handleIndex (D:\Projects\task\node_modules\mongoose\lib\document.js:971:14),    at model.$set (D:\Projects\task\node_modules\mongoose\lib\document.js:913:22),    at model.Document (D:\Projects\task\node_modules\mongoose\lib\document.js:135:12),    at model.Model (D:\Projects\task\node_modules\mongoose\lib\model.js:104:12),    at new model (D:\Projects\task\node_modules\mongoose\lib\model.js:4653:15),    at _callee3$ (D:\Projects\task\app/resolvers.js:63:27),    at tryCatch (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:45:40),    at Generator.invoke [as _invoke] (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:274:22),    at Generator.prototype.<computed> [as next] (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:97:21),    at asyncGeneratorStep (D:\Projects\task\app\resolvers.js:12:103),    at _next (D:\Projects\task\app\resolvers.js:14:194),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-19 03:01:44] GraphQLError: Syntax Error: Unexpected },    at syntaxError (D:\Projects\task\node_modules\graphql\error\syntaxError.js:15:10),    at Parser.unexpected (D:\Projects\task\node_modules\graphql\language\parser.js:1463:41),    at Parser.parseDefinition (D:\Projects\task\node_modules\graphql\language\parser.js:157:16),    at Parser.many (D:\Projects\task\node_modules\graphql\language\parser.js:1518:26),    at Parser.parseDocument (D:\Projects\task\node_modules\graphql\language\parser.js:111:25),    at Object.parse (D:\Projects\task\node_modules\graphql\language\parser.js:36:17),    at parse (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:428:22),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:237:35),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-19 03:01:51] GraphQLError: Syntax Error: Unexpected },    at syntaxError (D:\Projects\task\node_modules\graphql\error\syntaxError.js:15:10),    at Parser.unexpected (D:\Projects\task\node_modules\graphql\language\parser.js:1463:41),    at Parser.parseDefinition (D:\Projects\task\node_modules\graphql\language\parser.js:157:16),    at Parser.many (D:\Projects\task\node_modules\graphql\language\parser.js:1518:26),    at Parser.parseDocument (D:\Projects\task\node_modules\graphql\language\parser.js:111:25),    at Object.parse (D:\Projects\task\node_modules\graphql\language\parser.js:36:17),    at parse (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:428:22),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:237:35),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-19 03:02:08] GraphQLError: Syntax Error: Unexpected },    at syntaxError (D:\Projects\task\node_modules\graphql\error\syntaxError.js:15:10),    at Parser.unexpected (D:\Projects\task\node_modules\graphql\language\parser.js:1463:41),    at Parser.parseDefinition (D:\Projects\task\node_modules\graphql\language\parser.js:157:16),    at Parser.many (D:\Projects\task\node_modules\graphql\language\parser.js:1518:26),    at Parser.parseDocument (D:\Projects\task\node_modules\graphql\language\parser.js:111:25),    at Object.parse (D:\Projects\task\node_modules\graphql\language\parser.js:36:17),    at parse (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:428:22),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:237:35),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-19 03:02:08] GraphQLError: Syntax Error: Unexpected },    at syntaxError (D:\Projects\task\node_modules\graphql\error\syntaxError.js:15:10),    at Parser.unexpected (D:\Projects\task\node_modules\graphql\language\parser.js:1463:41),    at Parser.parseDefinition (D:\Projects\task\node_modules\graphql\language\parser.js:157:16),    at Parser.many (D:\Projects\task\node_modules\graphql\language\parser.js:1518:26),    at Parser.parseDocument (D:\Projects\task\node_modules\graphql\language\parser.js:111:25),    at Object.parse (D:\Projects\task\node_modules\graphql\language\parser.js:36:17),    at parse (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:428:22),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:237:35),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-19 03:03:27] GraphQLError: Syntax Error: Unexpected },    at syntaxError (D:\Projects\task\node_modules\graphql\error\syntaxError.js:15:10),    at Parser.unexpected (D:\Projects\task\node_modules\graphql\language\parser.js:1463:41),    at Parser.parseDefinition (D:\Projects\task\node_modules\graphql\language\parser.js:157:16),    at Parser.many (D:\Projects\task\node_modules\graphql\language\parser.js:1518:26),    at Parser.parseDocument (D:\Projects\task\node_modules\graphql\language\parser.js:111:25),    at Object.parse (D:\Projects\task\node_modules\graphql\language\parser.js:36:17),    at parse (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:428:22),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:237:35),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-19 03:03:29] GraphQLError: Syntax Error: Unexpected },    at syntaxError (D:\Projects\task\node_modules\graphql\error\syntaxError.js:15:10),    at Parser.unexpected (D:\Projects\task\node_modules\graphql\language\parser.js:1463:41),    at Parser.parseDefinition (D:\Projects\task\node_modules\graphql\language\parser.js:157:16),    at Parser.many (D:\Projects\task\node_modules\graphql\language\parser.js:1518:26),    at Parser.parseDocument (D:\Projects\task\node_modules\graphql\language\parser.js:111:25),    at Object.parse (D:\Projects\task\node_modules\graphql\language\parser.js:36:17),    at parse (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:428:22),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:237:35),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-19 03:04:27] GraphQLError: Syntax Error: Unexpected },    at syntaxError (D:\Projects\task\node_modules\graphql\error\syntaxError.js:15:10),    at Parser.unexpected (D:\Projects\task\node_modules\graphql\language\parser.js:1463:41),    at Parser.parseDefinition (D:\Projects\task\node_modules\graphql\language\parser.js:157:16),    at Parser.many (D:\Projects\task\node_modules\graphql\language\parser.js:1518:26),    at Parser.parseDocument (D:\Projects\task\node_modules\graphql\language\parser.js:111:25),    at Object.parse (D:\Projects\task\node_modules\graphql\language\parser.js:36:17),    at parse (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:428:22),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:237:35),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-19 03:04:28] GraphQLError: Syntax Error: Unexpected },    at syntaxError (D:\Projects\task\node_modules\graphql\error\syntaxError.js:15:10),    at Parser.unexpected (D:\Projects\task\node_modules\graphql\language\parser.js:1463:41),    at Parser.parseDefinition (D:\Projects\task\node_modules\graphql\language\parser.js:157:16),    at Parser.many (D:\Projects\task\node_modules\graphql\language\parser.js:1518:26),    at Parser.parseDocument (D:\Projects\task\node_modules\graphql\language\parser.js:111:25),    at Object.parse (D:\Projects\task\node_modules\graphql\language\parser.js:36:17),    at parse (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:428:22),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:237:35),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-19 03:04:29] GraphQLError: Syntax Error: Unexpected },    at syntaxError (D:\Projects\task\node_modules\graphql\error\syntaxError.js:15:10),    at Parser.unexpected (D:\Projects\task\node_modules\graphql\language\parser.js:1463:41),    at Parser.parseDefinition (D:\Projects\task\node_modules\graphql\language\parser.js:157:16),    at Parser.many (D:\Projects\task\node_modules\graphql\language\parser.js:1518:26),    at Parser.parseDocument (D:\Projects\task\node_modules\graphql\language\parser.js:111:25),    at Object.parse (D:\Projects\task\node_modules\graphql\language\parser.js:36:17),    at parse (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:428:22),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:237:35),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-19 03:04:30] GraphQLError: Syntax Error: Unexpected },    at syntaxError (D:\Projects\task\node_modules\graphql\error\syntaxError.js:15:10),    at Parser.unexpected (D:\Projects\task\node_modules\graphql\language\parser.js:1463:41),    at Parser.parseDefinition (D:\Projects\task\node_modules\graphql\language\parser.js:157:16),    at Parser.many (D:\Projects\task\node_modules\graphql\language\parser.js:1518:26),    at Parser.parseDocument (D:\Projects\task\node_modules\graphql\language\parser.js:111:25),    at Object.parse (D:\Projects\task\node_modules\graphql\language\parser.js:36:17),    at parse (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:428:22),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:237:35),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-19 03:05:11] GraphQLError: Syntax Error: Unexpected },    at syntaxError (D:\Projects\task\node_modules\graphql\error\syntaxError.js:15:10),    at Parser.unexpected (D:\Projects\task\node_modules\graphql\language\parser.js:1463:41),    at Parser.parseDefinition (D:\Projects\task\node_modules\graphql\language\parser.js:157:16),    at Parser.many (D:\Projects\task\node_modules\graphql\language\parser.js:1518:26),    at Parser.parseDocument (D:\Projects\task\node_modules\graphql\language\parser.js:111:25),    at Object.parse (D:\Projects\task\node_modules\graphql\language\parser.js:36:17),    at parse (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:428:22),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:237:35),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-19 03:05:23] GraphQLError: Cannot query field "mutation" on type "Mutation".,    at Object.Field (D:\Projects\task\node_modules\graphql\validation\rules\FieldsOnCorrectType.js:53:31),    at Object.enter (D:\Projects\task\node_modules\graphql\language\visitor.js:324:29),    at Object.enter (D:\Projects\task\node_modules\graphql\language\visitor.js:375:25),    at visit (D:\Projects\task\node_modules\graphql\language\visitor.js:242:26),    at Object.validate (D:\Projects\task\node_modules\graphql\validation\validate.js:73:24),    at validate (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:443:22),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:252:32),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-19 03:05:35] GraphQLError: Syntax Error: Unexpected },    at syntaxError (D:\Projects\task\node_modules\graphql\error\syntaxError.js:15:10),    at Parser.unexpected (D:\Projects\task\node_modules\graphql\language\parser.js:1463:41),    at Parser.parseDefinition (D:\Projects\task\node_modules\graphql\language\parser.js:157:16),    at Parser.many (D:\Projects\task\node_modules\graphql\language\parser.js:1518:26),    at Parser.parseDocument (D:\Projects\task\node_modules\graphql\language\parser.js:111:25),    at Object.parse (D:\Projects\task\node_modules\graphql\language\parser.js:36:17),    at parse (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:428:22),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:237:35),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-19 03:06:50] GraphQLError: Syntax Error: Unexpected },    at syntaxError (D:\Projects\task\node_modules\graphql\error\syntaxError.js:15:10),    at Parser.unexpected (D:\Projects\task\node_modules\graphql\language\parser.js:1463:41),    at Parser.parseDefinition (D:\Projects\task\node_modules\graphql\language\parser.js:157:16),    at Parser.many (D:\Projects\task\node_modules\graphql\language\parser.js:1518:26),    at Parser.parseDocument (D:\Projects\task\node_modules\graphql\language\parser.js:111:25),    at Object.parse (D:\Projects\task\node_modules\graphql\language\parser.js:36:17),    at parse (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:428:22),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:237:35),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-19 03:06:51] GraphQLError: Syntax Error: Unexpected },    at syntaxError (D:\Projects\task\node_modules\graphql\error\syntaxError.js:15:10),    at Parser.unexpected (D:\Projects\task\node_modules\graphql\language\parser.js:1463:41),    at Parser.parseDefinition (D:\Projects\task\node_modules\graphql\language\parser.js:157:16),    at Parser.many (D:\Projects\task\node_modules\graphql\language\parser.js:1518:26),    at Parser.parseDocument (D:\Projects\task\node_modules\graphql\language\parser.js:111:25),    at Object.parse (D:\Projects\task\node_modules\graphql\language\parser.js:36:17),    at parse (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:428:22),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:237:35),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-19 03:07:20] GraphQLError: Syntax Error: Unexpected },    at syntaxError (D:\Projects\task\node_modules\graphql\error\syntaxError.js:15:10),    at Parser.unexpected (D:\Projects\task\node_modules\graphql\language\parser.js:1463:41),    at Parser.parseDefinition (D:\Projects\task\node_modules\graphql\language\parser.js:157:16),    at Parser.many (D:\Projects\task\node_modules\graphql\language\parser.js:1518:26),    at Parser.parseDocument (D:\Projects\task\node_modules\graphql\language\parser.js:111:25),    at Object.parse (D:\Projects\task\node_modules\graphql\language\parser.js:36:17),    at parse (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:428:22),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:237:35),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-19 03:11:49] GraphQLError: Syntax Error: Unexpected },    at syntaxError (D:\Projects\task\node_modules\graphql\error\syntaxError.js:15:10),    at Parser.unexpected (D:\Projects\task\node_modules\graphql\language\parser.js:1463:41),    at Parser.parseDefinition (D:\Projects\task\node_modules\graphql\language\parser.js:157:16),    at Parser.many (D:\Projects\task\node_modules\graphql\language\parser.js:1518:26),    at Parser.parseDocument (D:\Projects\task\node_modules\graphql\language\parser.js:111:25),    at Object.parse (D:\Projects\task\node_modules\graphql\language\parser.js:36:17),    at parse (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:428:22),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:237:35),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-19 03:11:59] GraphQLError: Syntax Error: Unexpected },    at syntaxError (D:\Projects\task\node_modules\graphql\error\syntaxError.js:15:10),    at Parser.unexpected (D:\Projects\task\node_modules\graphql\language\parser.js:1463:41),    at Parser.parseDefinition (D:\Projects\task\node_modules\graphql\language\parser.js:157:16),    at Parser.many (D:\Projects\task\node_modules\graphql\language\parser.js:1518:26),    at Parser.parseDocument (D:\Projects\task\node_modules\graphql\language\parser.js:111:25),    at Object.parse (D:\Projects\task\node_modules\graphql\language\parser.js:36:17),    at parse (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:428:22),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:237:35),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-19 03:12:00] GraphQLError: Syntax Error: Unexpected },    at syntaxError (D:\Projects\task\node_modules\graphql\error\syntaxError.js:15:10),    at Parser.unexpected (D:\Projects\task\node_modules\graphql\language\parser.js:1463:41),    at Parser.parseDefinition (D:\Projects\task\node_modules\graphql\language\parser.js:157:16),    at Parser.many (D:\Projects\task\node_modules\graphql\language\parser.js:1518:26),    at Parser.parseDocument (D:\Projects\task\node_modules\graphql\language\parser.js:111:25),    at Object.parse (D:\Projects\task\node_modules\graphql\language\parser.js:36:17),    at parse (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:428:22),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:237:35),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-19 03:17:15] Error: author not passed!!!,    at _callee3$ (D:\Projects\task\app/resolvers.js:47:27),    at tryCatch (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:45:40),    at Generator.invoke [as _invoke] (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:274:22),    at Generator.prototype.<computed> [as next] (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:97:21),    at asyncGeneratorStep (D:\Projects\task\app\resolvers.js:12:103),    at _next (D:\Projects\task\app\resolvers.js:14:194),    at D:\Projects\task\app\resolvers.js:14:364,    at new Promise (<anonymous>),    at D:\Projects\task\app\resolvers.js:14:97,    at createPost (D:\Projects\task\app/resolvers.js:44:19),    at field.resolve (D:\Projects\task\node_modules\graphql-extensions\src\index.ts:274:18),    at resolveFieldValueOrError (D:\Projects\task\node_modules\graphql\execution\execute.js:467:18),    at resolveField (D:\Projects\task\node_modules\graphql\execution\execute.js:434:16),    at D:\Projects\task\node_modules\graphql\execution\execute.js:244:18,    at D:\Projects\task\node_modules\graphql\jsutils\promiseReduce.js:23:10,    at Array.reduce (<anonymous>)
error: [2020-03-19 03:28:09] GraphQLError: This anonymous operation must be the only defined operation.,    at Object.OperationDefinition (D:\Projects\task\node_modules\graphql\validation\rules\LoneAnonymousOperation.js:34:29),    at Object.enter (D:\Projects\task\node_modules\graphql\language\visitor.js:324:29),    at Object.enter (D:\Projects\task\node_modules\graphql\language\visitor.js:375:25),    at visit (D:\Projects\task\node_modules\graphql\language\visitor.js:242:26),    at Object.validate (D:\Projects\task\node_modules\graphql\validation\validate.js:73:24),    at validate (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:443:22),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:252:32),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-19 03:28:09] GraphQLError: This anonymous operation must be the only defined operation.,    at Object.OperationDefinition (D:\Projects\task\node_modules\graphql\validation\rules\LoneAnonymousOperation.js:34:29),    at Object.enter (D:\Projects\task\node_modules\graphql\language\visitor.js:324:29),    at Object.enter (D:\Projects\task\node_modules\graphql\language\visitor.js:375:25),    at visit (D:\Projects\task\node_modules\graphql\language\visitor.js:242:26),    at Object.validate (D:\Projects\task\node_modules\graphql\validation\validate.js:73:24),    at validate (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:443:22),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:252:32),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-19 03:34:48] GraphQLError: This anonymous operation must be the only defined operation.,    at Object.OperationDefinition (D:\Projects\task\node_modules\graphql\validation\rules\LoneAnonymousOperation.js:34:29),    at Object.enter (D:\Projects\task\node_modules\graphql\language\visitor.js:324:29),    at Object.enter (D:\Projects\task\node_modules\graphql\language\visitor.js:375:25),    at visit (D:\Projects\task\node_modules\graphql\language\visitor.js:242:26),    at Object.validate (D:\Projects\task\node_modules\graphql\validation\validate.js:73:24),    at validate (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:443:22),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:252:32),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at runMicrotasks (<anonymous>),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-19 03:34:48] GraphQLError: This anonymous operation must be the only defined operation.,    at Object.OperationDefinition (D:\Projects\task\node_modules\graphql\validation\rules\LoneAnonymousOperation.js:34:29),    at Object.enter (D:\Projects\task\node_modules\graphql\language\visitor.js:324:29),    at Object.enter (D:\Projects\task\node_modules\graphql\language\visitor.js:375:25),    at visit (D:\Projects\task\node_modules\graphql\language\visitor.js:242:26),    at Object.validate (D:\Projects\task\node_modules\graphql\validation\validate.js:73:24),    at validate (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:443:22),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:252:32),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at runMicrotasks (<anonymous>),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-19 03:35:52] GraphQLError: Syntax Error: Unexpected <EOF>,    at syntaxError (D:\Projects\task\node_modules\graphql\error\syntaxError.js:15:10),    at Parser.unexpected (D:\Projects\task\node_modules\graphql\language\parser.js:1463:41),    at Parser.parseDefinition (D:\Projects\task\node_modules\graphql\language\parser.js:157:16),    at Parser.many (D:\Projects\task\node_modules\graphql\language\parser.js:1518:26),    at Parser.parseDocument (D:\Projects\task\node_modules\graphql\language\parser.js:111:25),    at Object.parse (D:\Projects\task\node_modules\graphql\language\parser.js:36:17),    at parse (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:428:22),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:237:35),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at runMicrotasks (<anonymous>),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-19 03:39:07] CastError: Cast to ObjectId failed for value "{ id: '5e73712060df3d1dd8f02802' }" at path "authors" for model "Post",    at new CastError (D:\Projects\task\node_modules\mongoose\lib\error\cast.js:39:11),    at ObjectId.cast (D:\Projects\task\node_modules\mongoose\lib\schema\objectid.js:269:11),    at ObjectId.SchemaType.applySetters (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1010:12),    at ObjectId.SchemaType._castForQuery (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1424:15),    at ObjectId.SchemaType.castForQuery (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1414:15),    at D:\Projects\task\node_modules\mongoose\lib\schema\array.js:458:22,    at Array.map (<anonymous>),    at SchemaArray.castForQuery (D:\Projects\task\node_modules\mongoose\lib\schema\array.js:453:17),    at SchemaArray.SchemaType.castForQueryWrapper (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1393:15),    at cast (D:\Projects\task\node_modules\mongoose\lib\cast.js:315:32),    at model.Query.Query.cast (D:\Projects\task\node_modules\mongoose\lib\query.js:4685:12),    at model.Query.Query._castConditions (D:\Projects\task\node_modules\mongoose\lib\query.js:1862:10),    at model.Query.<anonymous> (D:\Projects\task\node_modules\mongoose\lib\query.js:1889:8),    at model.Query._wrappedThunk [as _find] (D:\Projects\task\node_modules\mongoose\lib\helpers\query\wrapThunk.js:16:8),    at D:\Projects\task\node_modules\kareem\index.js:369:33,    at processTicksAndRejections (internal/process/task_queues.js:75:11)
